name: rl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - networkx
  - numpy
  - pandas
  - scipy
  - pip
  - pip:
      - gymnasium
      - stable-baselines3
      - powerlaw

